### ISSUE TITLE
attachmentSHA256

### ISSUE THREAD

**Issue by Zeyshi** [scrapbird/sarlacc#1]
in storage.py line 185
attachmentSHA256 = self.get_sha256(b64encode(attachment["content"].encode("utf-8")))
should be:
attachmentSHA256 = self.get_sha256(b64**de**code(attachment["content"].encode("utf-8")))
to correctly get the final payload's hash (currently b64encodes the already b64encoded attachmant and calculates its hash)

**Comment by scrapbird** [comment]
Hah! Yeah I've noticed this thanks, I've fixed it in the plugin-api branch. I've been pretty busy this last week but will probably get it merged in in the next few days, there are quite a few changes I'm making to the plugin API and just want to finish them up before the merge.

**Comment by scrapbird** [comment]
@Zeyshi Scratch that, it's a fairly important issue so I just fixed it now.
